
Downloading and preparing dataset json/default to /Users/clementgillet/.cache/huggingface/datasets/json/default-de624a92592414c5/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96...
Downloading data files: 100%|██████████| 3/3 [00:00<00:00, 2906.66it/s]
Extracting data files: 100%|██████████| 3/3 [00:00<00:00, 44.82it/s]
Generating train split: 53865 examples [00:01, 37113.15 examples/s]

100%|██████████| 3/3 [00:00<00:00, 28.75it/s]
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/clementgillet/PycharmProjects/E-BART/e_bart/train.py", line 409, in <module>
    main()
  File "/Users/clementgillet/PycharmProjects/E-BART/e_bart/train.py", line 142, in main
    raw_guidance = load_dataset(
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/datasets/load.py", line 1785, in load_dataset
    builder_instance = load_dataset_builder(
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/datasets/load.py", line 1514, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/datasets/load.py", line 1143, in dataset_module_factory
    return PackagedDatasetModuleFactory(
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/datasets/load.py", line 723, in get_module
    data_files = DataFilesDict.from_local_or_remote(
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/datasets/data_files.py", line 792, in from_local_or_remote
    DataFilesList.from_local_or_remote(
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/datasets/data_files.py", line 748, in from_local_or_remote
    data_files = resolve_patterns_locally_or_by_urls(base_path, patterns, allowed_extensions)
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/datasets/data_files.py", line 348, in resolve_patterns_locally_or_by_urls
    for path in _resolve_single_pattern_locally(base_path, pattern, allowed_extensions):
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/datasets/data_files.py", line 292, in _resolve_single_pattern_locally
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to find '/Users/clementgillet/Desktop/4SUBMISSION/Guidance_Signal/GS2_guid/trainn.json' at /