WARNING:datasets.builder:Found cached dataset json (/Users/clementgillet/.cache/huggingface/datasets/json/default-bc7c43bbf08c9cab/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
100%|██████████| 3/3 [00:00<00:00, 48.01it/s]
WARNING:datasets.builder:Found cached dataset json (/Users/clementgillet/.cache/huggingface/datasets/json/default-f55bc7ce5c066cdf/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
100%|██████████| 3/3 [00:00<00:00, 40.18it/s]
Traceback (most recent call last):
  File "/Users/clementgillet/PycharmProjects/E-BART/e_bart/model/modeling_utils.py", line 2524, in from_pretrained
    resolved_archive_file = cached_file(pretrained_model_name_or_path, filename, **cached_file_kwargs)
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/netscratch/gillet/projects/model.bin'. Use `repo_type` argument if needed.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/clementgillet/PycharmProjects/E-BART/e_bart/train.py", line 408, in <module>
    main()
  File "/Users/clementgillet/PycharmProjects/E-BART/e_bart/train.py", line 161, in main
    model = BartForConditionalGeneration.from_pretrained(pretrained_model_name_or_path=pretrained_weights, config=my_config)
  File "/Users/clementgillet/PycharmProjects/E-BART/e_bart/model/modeling_utils.py", line 2596, in from_pretrained
    raise EnvironmentError(
OSError: Can't load the model for '/netscratch/gillet/projects/model.bin'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/netscratch/gillet/projects/model.bin' is the correct path to a directory containing a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.