WARNING:datasets.builder:Found cached dataset json (/Users/clementgillet/.cache/huggingface/datasets/json/default-de624a92592414c5/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
100%|██████████| 3/3 [00:00<00:00, 44.77it/s]
Downloading data files: 100%|██████████| 3/3 [00:00<00:00, 5309.25it/s]
Extracting data files: 100%|██████████| 3/3 [00:00<00:00, 174.13it/s]
100%|██████████| 3/3 [00:00<00:00, 214.01it/s]
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/clementgillet/PycharmProjects/E-BART/e_bart/train.py", line 409, in <module>
    main()
  File "/Users/clementgillet/PycharmProjects/E-BART/e_bart/train.py", line 147, in main
    raw_datasets["train"] = raw_datasets["train"].add_column("guidance", raw_guidance.data["train"]["guidance"])
  File "/Users/clementgillet/PycharmProjects/THESIS/venv/lib/python3.9/site-packages/datasets/table.py", line 472, in __getitem__
    return self.table[i]
  File "pyarrow/table.pxi", line 2987, in pyarrow.lib.Table.__getitem__
  File "pyarrow/table.pxi", line 4292, in pyarrow.lib.Table.column
  File "pyarrow/table.pxi", line 4233, in pyarrow.lib.Table._ensure_integer_index
KeyError: 'Field "guidance" does not exist in table schema'
Downloading and preparing dataset json/default to /Users/clementgillet/.cache/huggingface/datasets/json/default-9a249c13e446c85c/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96...
Dataset json downloaded and prepared to /Users/clementgillet/.cache/huggingface/datasets/json/default-9a249c13e446c85c/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96. Subsequent calls will reuse this data.